- name: Ensure the container file is present
  become: true
  ansible.builtin.copy:
    src: files/kepler.container
    dest: /usr/share/containers/systemd/kepler.container
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: reload systemd

- name: Start the Kepler container
  become: true
  ansible.builtin.systemd:
    name: kepler
    state: started
