- name: Ensure the container file is present
  become: true
  ansible.builtin.copy:
    src: kepler.container
    dest: /usr/share/containers/systemd/kepler.container
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start the Kepler container
  become: true
  ansible.builtin.systemd:
    name: kepler
    state: started
    daemon_reload: true

- name: Auto update
  become: true
  ansible.builtin.command: "podman auto-update"
  notify: restart kepler
